name = "press"
compatibility_date = "2021-09-27"
type = "webpack"

account_id = ""
workers_dev = true
routes = ["collected.press/*"]
zone_id = ""

[env.staging]
name = "collected-press-staging"
routes = ["staging.collected.press/*"]