name = "press"
main = "index.js"
compatibility_date = "2022-11-20"
usage_model = "unbound"
node_compat = true

workers_dev = true
routes = ["collected.press/*"]

[env.staging]
name = "collected-press-staging"
routes = ["staging.collected.press/*"]
node_compat = true

[dev]
port = 4321
